server:
  port: ${SERVER_PORT:${APP_PORT:8000}}

spring:
  application:
    name: ${APP_NAME:post-java-springboot-gradle-postgresql}
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pb_post}
    username: ${DB_USER:project_bible}
    password: ${DB_PASSWORD:project_bible}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /v3/api-docs
